import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bread-map",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=0c216456992257f7394332f18614f24a&libraries=services,clusterer&autoload=false`}
          strategy="beforeInteractive">
        </Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
